
package com.alex.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.alex.beans.Person;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonServiceImpl", targetNamespace = "http://service.alex.com")
@XmlSeeAlso({
    com.alex.beans.ObjectFactory.class,
    com.alex.service.ObjectFactory.class
})
public interface PersonServiceImpl {


    /**
     * 
     * @return
     *     returns java.util.List<com.alex.beans.Person>
     */
    @WebMethod
    @WebResult(name = "getAllPersonsReturn", targetNamespace = "http://service.alex.com")
    @RequestWrapper(localName = "getAllPersons", targetNamespace = "http://service.alex.com", className = "com.alex.service.GetAllPersons")
    @ResponseWrapper(localName = "getAllPersonsResponse", targetNamespace = "http://service.alex.com", className = "com.alex.service.GetAllPersonsResponse")
    public List<Person> getAllPersons();

    /**
     * 
     * @param id
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "deletePersonReturn", targetNamespace = "http://service.alex.com")
    @RequestWrapper(localName = "deletePerson", targetNamespace = "http://service.alex.com", className = "com.alex.service.DeletePerson")
    @ResponseWrapper(localName = "deletePersonResponse", targetNamespace = "http://service.alex.com", className = "com.alex.service.DeletePersonResponse")
    public boolean deletePerson(
        @WebParam(name = "id", targetNamespace = "http://service.alex.com")
        int id);

    /**
     * 
     * @param p
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "addPersonReturn", targetNamespace = "http://service.alex.com")
    @RequestWrapper(localName = "addPerson", targetNamespace = "http://service.alex.com", className = "com.alex.service.AddPerson")
    @ResponseWrapper(localName = "addPersonResponse", targetNamespace = "http://service.alex.com", className = "com.alex.service.AddPersonResponse")
    public boolean addPerson(
        @WebParam(name = "p", targetNamespace = "http://service.alex.com")
        Person p);

    /**
     * 
     * @param id
     * @return
     *     returns com.alex.beans.Person
     */
    @WebMethod
    @WebResult(name = "getPersonReturn", targetNamespace = "http://service.alex.com")
    @RequestWrapper(localName = "getPerson", targetNamespace = "http://service.alex.com", className = "com.alex.service.GetPerson")
    @ResponseWrapper(localName = "getPersonResponse", targetNamespace = "http://service.alex.com", className = "com.alex.service.GetPersonResponse")
    public Person getPerson(
        @WebParam(name = "id", targetNamespace = "http://service.alex.com")
        int id);

}
